-- MySQL Script generated by MySQL Workbench
-- Thu Oct  4 10:38:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema neuroteam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema neuroteam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neuroteam` DEFAULT CHARACTER SET utf8 ;
USE `neuroteam` ;

-- -----------------------------------------------------
-- Table `neuroteam`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Medico` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `licencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nss` VARCHAR(45) NULL,
  `edad` INT NULL,
  `genero` VARCHAR(10) NULL,
  `altura` DOUBLE NULL,
  `peso` DOUBLE NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Medico_has_Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Medico_has_Paciente` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Medico_has_Paciente` (
  `Medico_id` INT NOT NULL,
  `Paciente_id` INT NOT NULL,
  PRIMARY KEY (`Medico_id`, `Paciente_id`),
  INDEX `fk_Medico_has_Paciente_Paciente1_idx` (`Paciente_id` ASC),
  INDEX `fk_Medico_has_Paciente_Medico_idx` (`Medico_id` ASC),
  CONSTRAINT `fk_Medico_has_Paciente_Medico`
    FOREIGN KEY (`Medico_id`)
    REFERENCES `neuroteam`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Paciente_Paciente1`
    FOREIGN KEY (`Paciente_id`)
    REFERENCES `neuroteam`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Informe` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Informe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sintomas` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `Diagnostico` VARCHAR(45) NULL,
  `Medico_has_Paciente_Medico_id` INT NOT NULL,
  `Medico_has_Paciente_Paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Informe_Medico_has_Paciente1_idx` (`Medico_has_Paciente_Medico_id` ASC, `Medico_has_Paciente_Paciente_id` ASC),
  CONSTRAINT `fk_Informe_Medico_has_Paciente1`
    FOREIGN KEY (`Medico_has_Paciente_Medico_id` , `Medico_has_Paciente_Paciente_id`)
    REFERENCES `neuroteam`.`Medico_has_Paciente` (`Medico_id` , `Paciente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Tratamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Tratamiento` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Tratamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_ini` DATE NULL,
  `fecha_fin` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `posologia` VARCHAR(45) NULL,
  `Informe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tratamiento_Informe1_idx` (`Informe_id` ASC),
  CONSTRAINT `fk_Tratamiento_Informe1`
    FOREIGN KEY (`Informe_id`)
    REFERENCES `neuroteam`.`Informe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Prueba_medica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Prueba_medica` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Prueba_medica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `conclusion` VARCHAR(45) NULL,
  `Informe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prueba_medica_Informe1_idx` (`Informe_id` ASC),
  CONSTRAINT `fk_Prueba_medica_Informe1`
    FOREIGN KEY (`Informe_id`)
    REFERENCES `neuroteam`.`Informe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuroteam`.`Archivo_medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neuroteam`.`Archivo_medico` ;

CREATE TABLE IF NOT EXISTS `neuroteam`.`Archivo_medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NULL,
  `Prueba_medica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Archivo_medico_Prueba_medica1_idx` (`Prueba_medica_id` ASC),
  CONSTRAINT `fk_Archivo_medico_Prueba_medica1`
    FOREIGN KEY (`Prueba_medica_id`)
    REFERENCES `neuroteam`.`Prueba_medica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
